---
- name: Upgrade packages
  hosts: all
  become: true
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full
    - name: Manually update snaps
      shell: snap refresh
    - name: Remove unused packages and kernels
      apt:
        autoremove: yes
        autoclean: yes
    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Rebooting the server to apply updates
      reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists