---
- name: Upgrade packages
  hosts: all
  become: true
  tasks:
    - name: Update all packages to the latest version Debian
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full
      when: ansible_facts['os_family'] == "Debian"
    - name: Update all packages to the latest version RedHat
      ansible.builtin.dnf:
        update_cache: yes
        cache_valid_time: 3600
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
    - name: Remove unused packages and kernels Debian
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Remove unused packages and kernels RedHat
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_facts['os_family'] == "RedHat"    
    - name: Check if a reboot is required Debian
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
